name: Daily Build and Deploy

on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Dependencies
        run: yarn install
      - name: Build
        run: yarn build
      - name: Push List
        uses: garygrossgarten/github-action-scp@release
        with:
          local: cardano-token-list.json
          remote: /var/www/tokenlist/cardano-token-list.json
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          privateKey: ${{ secrets.KEY }}
