name: Update Submodules

on:
  schedule:
    - cron: '*/2 * * * *'

jobs:
  update-submodules:
    runs-on: ubuntu-latest

    steps:
      - name: Check Out Repository
        uses: actions/checkout@v2

      - name: Update Submodules
        run: |
          git submodule update --remote

      - name: Commit and Push Changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "Spectrum Labs Bot"
          git config user.email "admin@spectrumlabs.fi"
          git add .
          git commit -m "Update submodules"
          git push --set-upstream origin $GITHUB_REF