name: Update Submodule

on:
  schedule:
    - cron: '* * * * *'

jobs:
  update-submodule:
    runs-on: ubuntu-latest

    steps:
      - name: Check Out Repository
        uses: actions/checkout@v2

      - name: Update Submodules
        id: submodule_changes
        run: |
          git submodule update --init
          git submodule update --remote
          yarn install --frozen-lockfile
          yarn build

      - name: Publish The List
        uses: garygrossgarten/github-action-scp@release
        with:
          local: cardano-token-list.json
          remote: /var/www/tokenlist/cardano-token-list.json
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          privateKey: ${{ secrets.KEY }}
