name: Release token list
on:
  push:
    branches:
      - "main"
jobs:
  release:
    name: Publish Cardano Token List
    runs-on: ubuntu-latest
    steps:
      - name: Load Repo
        uses: actions/checkout@v3
      - name: Build
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - run: |
          yarn install --frozen-lockfile
          yarn build
      - name: Publish The List
        uses: garygrossgarten/github-action-scp@release
        with:
          local: cardano-token-list.json
          remote: /var/www/tokenlist/cardano-token-list.json
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          privateKey: ${{ secrets.KEY }}
      - name: Publish Schema
        uses: garygrossgarten/github-action-scp@release
        with:
          local: src/schema/tokenlist.cardano.schema.json
          remote: /var/www/tokenlist/tokenlist.cardano.schema.json
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          privateKey: ${{ secrets.KEY }}
